
inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'db/**/*.rb'
    - 'vendor/**/*'
    - 'lib/wp_data.rb'
    - 'app/models/search_builder.rb'

Metrics/ClassLength:
  Enabled: false