AllCops:
  DisplayCopNames: true
  Exclude:
    - 'db/**/*.rb'
    - 'vendor/**/*'
    - 'lib/wp_data.rb'
    - 'app/models/search_builder.rb'

Metrics/ClassLength:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

# method calls on an 'end' after a block
# we do this a lot, so leaving it
Style/MultilineBlockChain:
  Enabled: false

Style/Documentation:
  Enabled: false


# New Disables
Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/AlignHash:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/LineEndConcatenation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/IndentArray:
  Enabled: false

Lint/EndAlignment:
  Enabled: false

# this was set with a gigantic maximum.... so disabling
Metrics/AbcSize:
  Enabled: false

# got a lotta these
Style/GlobalVars:
  Enabled: false

Style/ClosingParenthesisIndentation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

# too opinionated
# Offense count: 12
Metrics/CyclomaticComplexity:
  Enabled: false


# Leaving these for now, not sure if this is a problem
# Offense count: 10
Metrics/PerceivedComplexity:
  Max: 20

Style/ClassAndModuleChildren:
  Exclude:
    - 'config/environment.rb'

# Offense count: 1
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Exclude:
    - 'spec/support/remote_ip_monkey_patch.rb'

# Offense count: 2
Lint/ShadowingOuterLocalVariable:
  Exclude:
    - 'config/environment.rb'

# assuming theres some reason for this one
# Offense count: 1
# Configuration parameters: AllowSafeAssignment.
Lint/AssignmentInCondition:
  Exclude:
    - 'bin/spring'

# good security reason for cop, but apparently useful in this context?
# Offense count: 1
Lint/Eval:
  Exclude:
    - 'app/controllers/api_controller.rb'

# outta the box
# Offense count: 2
Lint/HandleExceptions:
  Exclude:
    - 'bin/rails'
    - 'bin/rake'

# Offense count: 1
Lint/UselessAssignment:
  Exclude:
    - 'config/environment.rb'

Lint/IneffectiveAccessModifier:
  Exclude:
    - 'app/models/featured.rb'
    - 'scripts/lib/cleaner.rb'

# Offense count: 1
Style/AsciiComments:
  Exclude:
    - 'spec/lib/markdown_spec.rb'
