#!/bin/bash
HELP="AAPB init script\n\n

A basic CLI for managing AAPB \n\n

USAGE:\n\n

 \t ./aapb COMMAND [args] \n\n

COMMANDS:\n\n

\t  b | build \t  build the docker image\n
\t  c | cmd \t    run a bash command with the docker image\n
\t  d | dev \t    start a development server\n
\t  f | format \t run the rubocop formatter\n
\t  h | help \t   prints this help text\n
\t  t | test \t   run the test suite\n
"

DOCKER_RUN="docker run -it --rm --name aapb"
DOCKER_EXEC="docker exec -it"
VOLUME_MOUNT="-v $(pwd):/usr/src/app/"
PORT_MOUNT="-p 3000:3000 -p 8983:8983"

if [ -z $1 ]; then
  echo -e $HELP

elif [ $1 = "build" -o $1 = "b" ]; then
    shift
    docker build -t aapb . "$@"

elif [ $1 = "cmd" -o $1 = "c" ]; then
  shift
  CMD="$DOCKER_EXEC aapb"
  if [ -z $1 ]; then
    $CMD bash
  else $CMD "$@"
  fi

elif [ $1 = "dev" -o $1 = "d" ]; then
  shift
  $DOCKER_RUN $PORT_MOUNT $VOLUME_MOUNT aapb "$@"

elif [ $1 = "test" -o $1 = "t" ]; then
  shift
  $DOCKER_RUN aapb bundle exec rspec "$@"

elif [ $1 = "format" -o $1 = "f" ]; then
  shift
  $DOCKER_EXEC aapb rubocop --auto-correct "$@"

else 
  echo "Unrecognezed command: $@"
  echo -e $HELP

fi
