---
-
  id: cpb-aacip-50d685d2587
  url: https://www.bloomberg.com/news/videos/2016-11-16/the-david-rubenstein-show-eric-schmidt?srnd=peer-to-peer
-
  id: cpb-aacip-fadada16564
  url: https://www.bloomberg.com/news/videos/2016-11-23/the-david-rubenstein-show-indra-nooyi?srnd=peer-to-peer
-
  id: cpb-aacip-80ea7c79139
  url: https://www.bloomberg.com/news/videos/2016-11-09/the-david-rubenstein-show-kenneth-chenault?srnd=peer-to-peer
-
  id: cpb-aacip-3fa8c28a26b
  url: https://www.bloomberg.com/news/videos/2016-11-04/the-david-rubenstein-show-warren-buffett?srnd=peer-to-peer
-
  id: cpb-aacip-06a801715dd
  url: https://www.bloomberg.com/news/videos/2016-10-26/the-david-rubenstein-show-lloyd-blankfein?srnd=peer-to-peer
-
  id: cpb-aacip-d65f34b524a
  url: https://www.bloomberg.com/news/videos/2016-10-17/the-david-rubenstein-show-bill-gates?srnd=peer-to-peer
