name: ':bug: Bug Report'
description: Report a bug to help us improve
labels: Bug
body:
  - type: markdown
    attributes:
      value: |
        :bug: Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: ':lady_beetle: Please provide a clear and concise description of what the bug is.'
      placeholder: When I __________ it should  __________ but instead it __________
    validations:
      required: true

  - type: textarea
    id: reprod
    attributes:
      label: Reproduction steps
      description: ':clipboard: Please enter an explicit description of your issue.'
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: ':interrobang: A clear and concise description of what you expected to happen'
      placeholder: It should ...

  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots
      description: ':camera_flash: If applicable, add screenshots to help explain your problem.'
      value: |
        ![DESCRIPTION](LINK.png)
      render: bash

  - type: dropdown
    id: browsers
    attributes:
      label: Browsers
      description: ':computer: What browsers are you seeing the problem on?'
      multiple: true
      options:
        - Chrome
        - Firefox
        - Microsoft Edge
        - Safari
        - Opera
        - Other

  - type: dropdown
    id: os
    attributes:
      label: OS
      description: ':iphone: What is the impacted environment?'
      multiple: true
      options:
        - Android
        - iOS
        - Linux
        - Mac
        - Windows

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: ':information_desk_person: Add any other context here.'
      placeholder: Any other relevant information
