name: Feature request
description: Suggest an idea for this project
title: ''
body:
  - type: markdown
    attributes:
      value: |
        :building_construction: Thanks for taking the time to suggest a new feature!

        Please provide as much relevant detail as possible.

  - type: textarea
    id: summary
    description: ':pencil2: Briefly summarize your feature request'
    attributes:
      label: Summary
      placeholder: |
        As a [user]
        when I [action] 
        [result]

  - type: textarea
    id: related
    description: ':grey_question: Is this issue related to other existing issues? Please link them below'
    attributes:
      label: Related
      placeholder: Fixes [link to existing issue]

  - type: textarea
    id: alternatives
    description: ':part_alternation_mark: Describe alternatives you have considered'
    attributes:
      label: Alternatives
      placeholder: We could also ...

  - type: textarea
    id: context
    description: ':information_desk_person: Add any other context or screenshots about the feature request here.'
    attributes:
      label: Additional context
      placeholder: Due date, required for, blocked by ...
