# optional config for exhibits
"eotp":
  # preview:
  #   # fills in og: tags for fb link preview
  #   title: "Freedom Song: Interviews from Eyes on the Prize: America’s Civil Rights Years, 1954-1965"
  #   description: "This curated collection features the unedited interviews conducted during the making of the landmark PBS documentary series Eyes on the Prize: America’s Civil Rights Years, 1954–1965 (1987)."
  #   image: "https://s3.amazonaws.com/americanarchive.org/special-collections/EyesOnThePrize_Logo.jpg"
  sections:
  - "eotp/1-framing-civil-rights-past"
  - "eotp/2-making-television-history"
  - "eotp/3-timeline-of-events"
  - "eotp/4-locating-the-movement"
  - "eotp/5-interview-subjects"
  - "eotp/5-1-local-people"
  - "eotp/5-2-women"
  - "eotp/5-3-organizational-activists"
  - "eotp/5-4-officials"
  - "eotp/5-5-media"
  - "eotp/5-6-religious-leaders"
  - "eotp/5-7-labor-business"
  - "eotp/5-8-students-educators"
"peabody":
  sections:
  - "peabody/year"
  - "peabody/location"
  - "peabody/entry-category"
  - "peabody/winners"
  - "peabody/history-peabody"
  - "peabody/peabody-uga"
"native-narratives":
  sections:
  - "native-narratives/misrepresentations"
  - "native-narratives/termination-relocation-restoration"
  - "native-narratives/aim"
  - "native-narratives/contemporary-news"
  - "native-narratives/visual-sovereignty"
"climate-change":
  sections:
  - climate-change/history
  - climate-change/causes
  - climate-change/impacts
  - climate-change/advocacy
  - climate-change/communicating-art
  - climate-change/solutions
"station-histories":
  sections:
  - station-histories/first-broadcasts
  - station-histories/dedication-ceremonies
  - station-histories/restrospective-anniversaries
  - station-histories/public-broadcasting-act
"presidential-elections":
  sections:
  - presidential-elections/process
  - presidential-elections/candidates
  - presidential-elections/voters-issues
"black-power":
  sections:
  - black-power/black-journal
  - black-power/soul
"conservatism":
  sections:
  - conservatism/politics-net
  - conservatism/defining-conservatism
  - conservatism/conservatism-gop
  - conservatism/conservatism-civil-rights
  - conservatism/conservatism-media
"first-amendment":
  sections:
  - first-amendment/protesting-activities
  - first-amendment/protests-60s-70s
  - first-amendment/protests-80s-andbeyond
"historic-preservation":
  sections:
  - historic-preservation/traditional-preservation
  - historic-preservation/marginalized-perspectives
  - historic-preservation/urban-renewal
  - historic-preservation/economic
  - historic-preservation/natural-environment
"civil-rights":
  sections:
  - civil-rights/places
  - civil-rights/organizations
  - civil-rights/people
"watergate":
  sections:
  - watergate/the-watergate-scandal-1972-1974
  - watergate/watergate-and-public-broadcasting
  - watergate/cast-of-characters
  - watergate/the-watergate-coverage
  - watergate/the-impeachment-coverage
  - watergate/additional-resources
"education":
  sections:
  - education/education-documentaries-in-the-net-years-1953-1972
  - education/capturing-education-battles-on-television-1972-1980
  - education/covering-education-in-the-1980s
  - education/national-education-reforms-on-local-television-1990-today
"newsmagazines":
  sections:
  - newsmagazines/precedents
  - newsmagazines/definitive-newsmags
"latino-empowerment":
  sections:
  - latino-empowerment/2-origins-of-latino-community-radio
  - latino-empowerment/3-latino-public-television-history
  - latino-empowerment/4-the-immigrant-experience-through-public-broadcasting
  - latino-empowerment/5-voices-of-dissent
  - latino-empowerment/6-identity-and-culture
"zoom":
  sections:
  - zoom/innovations-childrens-television
  - zoom/children-cultural-producers
  - zoom/politics-zoom
"wrvr":
  sections:
  - "wrvr/2-wrvr-religious-broadcasting"
  - "wrvr/3-wrvr-public-affairs"
  - "wrvr/4-covering-civil-rights-anti-war-movements"
  - "wrvr/5-black-manifesto"
  - "wrvr/6-cultural-programming-music"
"le-show":
  sections:
  - "le-show/2-harry-shearer-creative-life"
  - "le-show/3-brief-historical-overview-of-le-show"
  - "le-show/4-le-show-sampler"
  - "le-show/4-1-presidential-satire"
  - "le-show/4-2-satires-of-commercial-public-media"
  - "le-show/4-3-cultural-criticism"
  - "le-show/4-4-environmental-reporting"
  - "le-show/4-5-more-satire-in-song"
  - "le-show/5-le-show-interviews"
  - "le-show/7-le-show-by-shearer"
  - "le-show/6-acknowledgements"
"after-the-fire":
  sections: 
  - "after-the-fire/2-la-riots"
  - "after-the-fire/3-occupy-wall-street"
  - "after-the-fire/4-ferguson"
  - "after-the-fire/5-baltimore"
  - "after-the-fire/6-charlottesville"
  - "after-the-fire/7-annotated-list-of-events"
"empoderamiento-latino":
  sections:
  - empoderamiento-latino/2-los-origines-de-la-radio-communidad-latina
  - empoderamiento-latino/3-historia-de-la-television-publica-latina
  - empoderamiento-latino/4-la-experiencia-de-inmigracion-a-traves-de-la-radiodifusion-publica
  - empoderamiento-latino/5-voces-de-desacuerdo
  - empoderamiento-latino/6-identidad-y-cultura
"odyssey-of-black-studies-in-public-broadcasting":
  sections:
  - "odyssey-of-black-studies-in-public-broadcasting/2-the-formative-years"
  - "odyssey-of-black-studies-in-public-broadcasting/3-black-students-and-faculty-in-higher-education"
  - "odyssey-of-black-studies-in-public-broadcasting/4-black-studies-at-50"
"interviews-with-foreign-leaders":
  sections:
  - "interviews-with-foreign-leaders/2-people"
  - "interviews-with-foreign-leaders/3-country"
  - "interviews-with-foreign-leaders/4-date"
"stories-of-the-land":
  sections:
  - "stories-of-the-land/2-land"
  - "stories-of-the-land/3-work"
  - "stories-of-the-land/4-environment"
  - "stories-of-the-land/5-culture"
  - "stories-of-the-land/6-practice"
  - "stories-of-the-land/7-politics"
  - "stories-of-the-land/8-additional-reading"  
"witnessing-new-mexico"
  sections: 
  - "witnessing-new-mexico/2-reclaiming-histories"
  - "witnessing-new-mexico/3-sharing-stories"
  - "witnessing-new-mexico/4-navigating-racism"
"hiv-aids-and-public-broadcasting":
  sections: 
  - "hiv-aids-and-public-broadcasting/2-1981-1985-early-reporting-on-the-gay-disease"
  - "hiv-aids-and-public-broadcasting/3-1986-1988-the-aids-special-program"
  - "hiv-aids-and-public-broadcasting/4-1989-1994-into-the-second-decade"
  - "hiv-aids-and-public-broadcasting/5-1989-1991-broadcasting-act-up-direct-action"
  - "hiv-aids-and-public-broadcasting/6-1995-1997-new-hiv-aids-therapies-and-strategies"
  - "hiv-aids-and-public-broadcasting/7-public-broadcasting-covers-the-hiv-aids-pandemic-in-africa"
  - "hiv-aids-and-public-broadcasting/8-national-programs"
  - "hiv-aids-and-public-broadcasting/9-additional-programs"
  - "hiv-aids-and-public-broadcasting/10-epilogue"
