# Jetty params default to the same values for both `development` and `test`
# environments. Override any of the defaults with environment variables.
default: &default
  startup_wait: <%= ENV['JETTY_STARTUP_WAIT'] || 15 %>
  jetty_port: <%= ENV['JETTY_PORT'] || 8983 %>
  jetty_home: <%= ENV['JETTY_HOME'] || File.expand_path(File.join(File.dirname(File.dirname(__FILE__)), 'jetty')) %>
  solr_core: <%= ENV['SOLR_CORE'] || 'blacklight-core' %>
development:
  <<: *default
test:
  <<: *default