name: 🪂 Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types: [published, edited, prereleased]
  workflow_dispatch:

jobs:
  build:
    name: 🔨 Build and deploy docker image
    uses: WGBH-MLA/.github/.github/workflows/build.yml@main
